# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf3fa8b9c250ea7a8f7cdbac722946e1499fe4cdb2895473fec933dd62973915d98c917a822936ff64a4b6c1315c6b3ab9cce2e575e81fe85493eab3763fdce1

test:
  secret_key_base: 19e9603c85d54d65ec02727adbf00719a3779430688fef53e418631b5aad8a40fe93674c1d950d0753cbd6fabe6fc1215bd2952fc1f18346830500e9352fac8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
