# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2829c0cb9c0215d2453c6a31fc211183972f7e05a8e050df63da24ed67d5ce7c5582d66bf1a0f597dfc696c797ba2b6ab9ccd475b0f4545c7f5fd1f677cda9a4

test:
  secret_key_base: 6f651f6fc4fb1ced089aa5faf3dcedf3e8170261f43bf6b1495b683419d876499ef697965626197591313df252dc46667e00cfcb3affed3df126831379053d1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
